export const ADDTEN = 'ADDTEN'
export const SUBTEN = 'SUBTEN'
export const ADD = 'ADD'
export const SUB = 'SUB'
export const STORE_RESULT = 'STORE_RESULT'
export const DELETE_RESULT = 'DELETE_RESULT'
